[package]
name = "colmena"
version = "0.1.0"
authors = ["Zhaofeng Li <hello@zhaofeng.li>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
clap = "2.33.3"
console = "0.13.0"
futures = "0.3.8"
glob = "0.3.0"
indicatif = "0.15.0"
log = "0.4.11"
quit = "1.1.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0"
snafu = "0.6.10"
tempfile = "3.1.0"
tokio = { version = "0.3.6", features = ["full"] }
